[2025-09-15T19:23:03.172+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:23:05.075+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [queued]>
[2025-09-15T19:23:05.100+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [queued]>
[2025-09-15T19:23:05.101+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-15T19:23:05.133+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonSensor): wait_for_kafka> on 2025-09-15 18:52:37.260987+00:00
[2025-09-15T19:23:05.159+0000] {standard_task_runner.py:57} INFO - Started process 397 to run task
[2025-09-15T19:23:05.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'wait_for_kafka', 'scheduled__2025-09-15T18:52:37.260987+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmply48e27r']
[2025-09-15T19:23:05.205+0000] {standard_task_runner.py:85} INFO - Job 409: Subtask wait_for_kafka
[2025-09-15T19:23:05.404+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:23:05.889+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [running]> on host 4ba3580a27fc
[2025-09-15T19:23:05.996+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:23:06.998+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='wait_for_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T18:52:37.260987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T18:52:37.260987+00:00'
[2025-09-15T19:23:07.009+0000] {python.py:72} INFO - Poking callable: <function check_kafka_message at 0x7fb12c3e5a70>
[2025-09-15T19:23:07.129+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:23:08.143+0000] {client_async.py:795} WARNING - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]> timed out after 1000.0 ms. Closing connection.
[2025-09-15T19:23:08.144+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 1000.0 ms
[2025-09-15T19:23:08.147+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:23:08.649+0000] {client_async.py:795} WARNING - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]> timed out after 500.0 ms. Closing connection.
[2025-09-15T19:23:08.673+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 500.0 ms
[2025-09-15T19:23:08.688+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:23:08.952+0000] {client_async.py:795} WARNING - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]> timed out after 250.0 ms. Closing connection.
[2025-09-15T19:23:08.984+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 250.0 ms
[2025-09-15T19:23:09.034+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:23:09.093+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 225, in execute
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 212, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/python.py", line 73, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_utils.py", line 213, in check_kafka_message
    consumer_timeout_ms=5000
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-09-15T19:23:09.204+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_postgres_batch, task_id=wait_for_kafka, execution_date=20250915T185237, start_date=20250915T192305, end_date=20250915T192309
[2025-09-15T19:23:09.260+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 409 for task wait_for_kafka (NoBrokersAvailable; 397)
[2025-09-15T19:23:09.299+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-15T19:23:09.379+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
