[2025-09-03T19:39:08.619+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T19:39:08.648+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres.create_dds_tables scheduled__2025-09-02T20:30:00+00:00 [queued]>
[2025-09-03T19:39:08.677+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres.create_dds_tables scheduled__2025-09-02T20:30:00+00:00 [queued]>
[2025-09-03T19:39:08.679+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-03T19:39:08.740+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_dds_tables> on 2025-09-02 20:30:00+00:00
[2025-09-03T19:39:08.756+0000] {standard_task_runner.py:57} INFO - Started process 1881 to run task
[2025-09-03T19:39:08.772+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres', 'create_dds_tables', 'scheduled__2025-09-02T20:30:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp3z2ccq9d']
[2025-09-03T19:39:08.780+0000] {standard_task_runner.py:85} INFO - Job 236: Subtask create_dds_tables
[2025-09-03T19:39:08.835+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T19:39:08.976+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres.create_dds_tables scheduled__2025-09-02T20:30:00+00:00 [running]> on host 566c672cfab0
[2025-09-03T19:39:09.031+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T19:39:09.266+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres' AIRFLOW_CTX_TASK_ID='create_dds_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T20:30:00+00:00'
[2025-09-03T19:39:09.268+0000] {sql.py:265} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS dds.users (
            id SERIAL PRIMARY KEY,
            user_id INT UNIQUE
        );

        CREATE TABLE IF NOT EXISTS dds.facts_events (
            id SERIAL PRIMARY KEY,
            user_id INT REFERENCES dds.users(id),
            event_type_id INT REFERENCES dictionary.event_types(id),
            city_id INT REFERENCES dictionary.cities(id),
            lat DOUBLE PRECISION,
            lon DOUBLE PRECISION,
            cost_usd NUMERIC(10,2),
            cost_eur NUMERIC(10,2),
            cost_rub NUMERIC(10,2),
            weather_temp NUMERIC(5,2),
            weather_desc TEXT,
            timestamp TIMESTAMPTZ
        );
        
[2025-09-03T19:39:09.298+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T19:39:12.196+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T19:39:12.223+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS dds.users (
            id SERIAL PRIMARY KEY,
            user_id INT UNIQUE
        );

        CREATE TABLE IF NOT EXISTS dds.facts_events (
            id SERIAL PRIMARY KEY,
            user_id INT REFERENCES dds.users(id),
            event_type_id INT REFERENCES dictionary.event_types(id),
            city_id INT REFERENCES dictionary.cities(id),
            lat DOUBLE PRECISION,
            lon DOUBLE PRECISION,
            cost_usd NUMERIC(10,2),
            cost_eur NUMERIC(10,2),
            cost_rub NUMERIC(10,2),
            weather_temp NUMERIC(5,2),
            weather_desc TEXT,
            timestamp TIMESTAMPTZ
        );
        , parameters: None
[2025-09-03T19:39:13.418+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(users, 16954) already exists.

[2025-09-03T19:39:13.453+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_postgres, task_id=create_dds_tables, execution_date=20250902T203000, start_date=20250903T193908, end_date=20250903T193913
[2025-09-03T19:39:13.501+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 236 for task create_dds_tables (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(users, 16954) already exists.
; 1881)
[2025-09-03T19:39:13.564+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-03T19:39:13.633+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
