[2025-09-16T10:10:28.967+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T10:10:29.526+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-16T09:40:22.832240+00:00 [queued]>
[2025-09-16T10:10:29.663+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-16T09:40:22.832240+00:00 [queued]>
[2025-09-16T10:10:29.674+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-16T10:10:29.870+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonSensor): wait_for_kafka> on 2025-09-16 09:40:22.832240+00:00
[2025-09-16T10:10:30.270+0000] {standard_task_runner.py:57} INFO - Started process 247 to run task
[2025-09-16T10:10:30.295+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'wait_for_kafka', 'scheduled__2025-09-16T09:40:22.832240+00:00', '--job-id', '651', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp6vs3e88d']
[2025-09-16T10:10:30.337+0000] {standard_task_runner.py:85} INFO - Job 651: Subtask wait_for_kafka
[2025-09-16T10:10:30.832+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T10:10:31.166+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-16T09:40:22.832240+00:00 [running]> on host 71d7292233fc
[2025-09-16T10:10:31.275+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-16T10:10:31.922+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='wait_for_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T09:40:22.832240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-16T09:40:22.832240+00:00'
[2025-09-16T10:10:31.928+0000] {python.py:72} INFO - Poking callable: <function check_kafka_message at 0x7efc4cf06f80>
[2025-09-16T10:10:35.963+0000] {conn.py:1521} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -3] Temporary failure in name resolution. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-16T10:10:35.964+0000] {conn.py:324} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [unspecified None]>: DNS lookup failed for kafka:29092 (AddressFamily.AF_UNSPEC)
[2025-09-16T10:10:35.965+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-09-16T10:10:35.967+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 225, in execute
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 212, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/python.py", line 73, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_utils.py", line 227, in check_kafka_message
    consumer_timeout_ms=5000
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-09-16T10:10:36.772+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_postgres_batch, task_id=wait_for_kafka, execution_date=20250916T094022, start_date=20250916T101029, end_date=20250916T101036
[2025-09-16T10:10:36.890+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 651 for task wait_for_kafka (NoBrokersAvailable; 247)
[2025-09-16T10:10:36.949+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-16T10:10:37.034+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
