[2025-09-03T16:24:01.189+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.consume_and_save_batch manual__2025-09-03T16:09:02.435208+00:00 [queued]>
[2025-09-03T16:24:02.656+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.consume_and_save_batch manual__2025-09-03T16:09:02.435208+00:00 [queued]>
[2025-09-03T16:24:02.657+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2025-09-03T16:24:03.097+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): consume_and_save_batch> on 2025-09-03 16:09:02.435208+00:00
[2025-09-03T16:24:03.160+0000] {standard_task_runner.py:57} INFO - Started process 296 to run task
[2025-09-03T16:24:03.398+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'consume_and_save_batch', 'manual__2025-09-03T16:09:02.435208+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpxdmo1dr1']
[2025-09-03T16:24:03.455+0000] {standard_task_runner.py:85} INFO - Job 157: Subtask consume_and_save_batch
[2025-09-03T16:24:08.378+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T16:24:09.251+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.consume_and_save_batch manual__2025-09-03T16:09:02.435208+00:00 [running]> on host 5646b9718ecc
[2025-09-03T16:24:11.478+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='consume_and_save_batch' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T16:09:02.435208+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T16:09:02.435208+00:00'
[2025-09-03T16:24:11.494+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:11.497+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:11.507+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:11.513+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.03 secs
[2025-09-03T16:24:11.546+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:11.548+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:11.549+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:11.550+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.09 secs
[2025-09-03T16:24:11.647+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:11.648+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:11.649+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:11.650+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.23 secs
[2025-09-03T16:24:11.881+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:11.882+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:11.883+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:11.885+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.42 secs
[2025-09-03T16:24:12.307+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:12.308+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:12.309+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:12.310+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.87 secs
[2025-09-03T16:24:13.182+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-03T16:24:13.184+0000] {conn.py:430} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-09-03T16:24:13.185+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T16:24:13.186+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.31 secs
[2025-09-03T16:24:13.499+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_utils.py", line 27, in consume_and_save
    group_id="airflow_batch_consumer"
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/consumer/group.py", line 387, in __init__
    self._client = self.config['kafka_client'](metrics=self._metrics, **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-09-03T16:24:13.573+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=kafka_to_postgres_batch, task_id=consume_and_save_batch, execution_date=20250903T160902, start_date=20250903T162401, end_date=20250903T162413
[2025-09-03T16:24:13.845+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 157 for task consume_and_save_batch (NoBrokersAvailable; 296)
[2025-09-03T16:24:13.920+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-09-03T16:24:14.079+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
